console.log('🎮 Node.js Game Hub - In-Memory Version');
console.log('=====================================');
console.log('');
console.log('✅ This version uses in-memory storage for simplicity');
console.log('📊 Sample content is automatically created when server starts');
console.log('🚀 Ready to run! Use: npm start');
console.log('');
console.log('💡 Features available:');
console.log('   • Real-time content synchronization');
console.log('   • Cross-platform hotspot detection');
console.log('   • WiFi QR code generation');
console.log('   • Mobile device tracking');
console.log('   • Content management interface');
console.log('');
console.log('⚠️  Note: Data is not persisted between server restarts');
console.log('   This is perfect for testing and proof of concept!'); 